name: Deploy
on:
  push:
    branches: Datapacks
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: deploy
        uses:  swznd/sftp-deploy@master
        with:
          host: ${{ secrets.SFTP_IP }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          remote_path: /Creative_Olympics/datapacks
          ignore: .github/**,.gitignore,**/.gitignore,**/.git/**, entities/**, poi/**, region/**, README.md, icon.png, level.dat, session.lock
